//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForestryClubApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact_Table
    {
        public int Contact_id { get; set; }

        [Required(ErrorMessage ="Required")]
        [Display(Name ="Name")]
        public string Person_Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Email")]
        public string Person_Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Mobile")]
        public string Person_Mobile { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Department")]
        public string Department { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Batch")]
        public string Batch { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Message")]
        public string Message { get; set; }
    }
}
