//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForestryClubApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_Table
    {
        public int House_id { get; set; }
        public string House_Name { get; set; }
        public string House_Leader { get; set; }
        public string Batch { get; set; }
        public int cat_fid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
